import express from "express";
import cors from "cors";
import pg from "pg";
const {Pool}=pg;
const app=express();
app.use(cors());app.use(express.json());
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.get('/health',async(_req,res)=>{try{await pool.query('select 1');res.json({ok:true,service:'hair-salon-api'});}catch(e){res.status(503).json({ok:false});}});
app.get('/api/outlets',async(_req,res)=>{try{const {rows}=await pool.query('select id,name,city,active from hair_salon.outlets where active=true order by name');res.json(rows);}catch(e){res.status(500).json({error:'Unable to load outlets'});}});
app.listen(process.env.PORT||10000,()=>console.log('Hair Salon API running'));
