'use client';
import{useEffect,useState}from'react';import{ArrowLeft,Building2,Plus,Scissors,Users,UserPlus,Check,Trash2}from'lucide-react';import{useRouter}from'next/navigation';import{supabase,supabasePublic}from'../../../lib/supabase';
export default function Management(){const r=useRouter();const[outs,setOuts]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[on,setOn]=useState(''),[city,setCity]=useState('Mandsaur'),[sn,setSn]=useState(''),[price,setPrice]=useState(''),[oid,setOid]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[role,setRole]=useState('staff'),[staffOutlet,setStaffOutlet]=useState(''),[selectedStaff,setSelectedStaff]=useState(''),[assigned,setAssigned]=useState<string[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
const load=async()=>{const{data:p}=await supabasePublic.rpc('get_my_profile');const me=Array.isArray(p)?p[0]:p;if(!me||me.role==='staff'){r.replace('/staff');return}const[o,s,v]=await Promise.all([supabase.rpc('owner_list_outlets'),supabase.from('profiles').select('id,name,role,active,outlet_id').in('role',['staff','manager']).order('name'),supabase.from('services').select('*').order('name')]);setOuts(o.data||[]);setStaff(s.data||[]);setServices(v.data||[]);if(!oid&&o.data?.[0])setOid(o.data[0].id);if(!staffOutlet&&o.data?.[0])setStaffOutlet(o.data[0].id)};
useEffect(()=>{const saved=localStorage.getItem('hair_salon_outlet');load()},[]);
async function addO(){setMsg('');if(!on.trim())return;const{error}=await supabase.rpc('owner_add_outlet',{p_name:on.trim(),p_city:city.trim()||'Mandsaur'});if(error)setMsg(error.message);else{setOn('');await load()}}
async function deleteOutlet(id:string){if(!confirm('Delete this outlet? This is allowed only when it has no staff, services, customers, or transactions.'))return;setMsg('');const{error}=await supabase.rpc('owner_delete_outlet',{p_outlet_id:id});if(error)setMsg(error.message);else{if(localStorage.getItem('hair_salon_outlet')===id)localStorage.removeItem('hair_salon_outlet');setMsg('Outlet deleted.');await load()}}\nasync function addS(){setMsg('');if(!sn.trim()||!oid||price==='')return;const{error}=await supabase.from('services').insert({name:sn.trim(),price:Number(price),outlet_id:oid,active:true});if(error)setMsg(error.message);else{setSn('');setPrice('');await load()}}
async function createUser(){setMsg('');if(!name.trim()||!email.trim()||pass.length<6||!staffOutlet){setMsg('Enter name, email, password (6+ chars) and outlet.');return}setBusy(true);const{data,error}=await supabase.functions.invoke('create-salon-user',{body:{name:name.trim(),email:email.trim(),password:pass,role,outlet_id:staffOutlet}});setBusy(false);if(error||data?.error){setMsg(error?.message||data?.error||'Could not create user.');return}setName('');setEmail('');setPass('');setMsg('User created successfully.');await load()}
async function loadAssignments(id:string){setSelectedStaff(id);const{data}=await supabase.from('staff_services').select('service_id').eq('staff_id',id);setAssigned((data||[]).map(x=>x.service_id))}
async function toggleAssignment(serviceId:string){if(!selectedStaff)return;const has=assigned.includes(serviceId);if(has){await supabase.from('staff_services').delete().eq('staff_id',selectedStaff).eq('service_id',serviceId);setAssigned(a=>a.filter(x=>x!==serviceId))}else{await supabase.from('staff_services').insert({staff_id:selectedStaff,service_id:serviceId});setAssigned(a=>[...a,serviceId])}}
async function toggleUser(s:any){await supabase.from('profiles').update({active:!s.active}).eq('id',s.id);await load()}
const selected=staff.find(x=>x.id===selectedStaff);const visibleServices=selected?.outlet_id?services.filter(x=>x.outlet_id===selected.outlet_id):services;
return <main className="min-h-screen bg-[#f5f1ea] p-5 md:p-8"><div className="mx-auto max-w-7xl"><button onClick={()=>r.push('/dashboard')} className="mb-6 flex items-center gap-2 text-sm"><ArrowLeft size={16}/> Dashboard</button><p className="text-xs font-bold uppercase tracking-[.25em] text-[#b88a45]">Owner administration</p><h1 className="mt-2 text-4xl font-bold">Outlets, team & services</h1>{msg&&<div className="mt-5 rounded-2xl bg-white p-4 text-sm">{msg}</div>}
<div className="mt-8 grid gap-6 xl:grid-cols-3">
<section className="rounded-3xl border border-[#e5ddd2] bg-white p-6"><div className="flex items-center gap-3"><Building2/><h2 className="font-bold">Outlets</h2></div><div className="mt-5 space-y-3"><input value={on} onChange={e=>setOn(e.target.value)} placeholder="New outlet name" className="w-full rounded-2xl border px-4 py-3"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City" className="w-full rounded-2xl border px-4 py-3"/><button onClick={addO} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#17130f] py-3 font-semibold text-white"><Plus size={17}/> Add outlet</button></div><div className="mt-6 space-y-2">{outs.map(o=><button key={o.id} onClick={()=>{localStorage.setItem('hair_salon_outlet',o.id);r.push('/dashboard')}} className={`flex w-full items-center justify-between rounded-2xl p-4 text-left ${oid===o.id?'bg-[#17130f] text-white':'bg-[#f5f1ea]'}`}><span><b>{o.name}</b><span className="ml-2 text-xs opacity-60">{o.city}</span></span><span className="flex items-center gap-3">{oid===o.id&&<Check size={17}/>}<span role="button" onClick={e=>{e.stopPropagation();deleteOutlet(o.id)}} className="rounded-xl p-2 text-red-600 hover:bg-red-50"><Trash2 size={16}/></span></span></button>)}</div></section>
<section className="rounded-3xl border border-[#e5ddd2] bg-white p-6"><div className="flex items-center gap-3"><UserPlus/><h2 className="font-bold">Add staff / manager</h2></div><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="w-full rounded-2xl border px-4 py-3"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Login email" className="w-full rounded-2xl border px-4 py-3"/><input value={pass} onChange={e=>setPass(e.target.value)} type="password" placeholder="Temporary password" className="w-full rounded-2xl border px-4 py-3"/><select value={role} onChange={e=>setRole(e.target.value)} className="w-full rounded-2xl border bg-white px-4 py-3"><option value="staff">Staff</option><option value="manager">Manager</option></select><select value={staffOutlet} onChange={e=>setStaffOutlet(e.target.value)} className="w-full rounded-2xl border bg-white px-4 py-3"><option value="">Assign outlet</option>{outs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><button disabled={busy} onClick={createUser} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#17130f] py-3 font-semibold text-white disabled:opacity-50"><Plus size={17}/>{busy?'Creating…':'Create login'}</button></div></section>
<section className="rounded-3xl border border-[#e5ddd2] bg-white p-6"><div className="flex items-center gap-3"><Users/><h2 className="font-bold">Team</h2></div><div className="mt-5 space-y-2">{staff.map(s=><button key={s.id} onClick={()=>loadAssignments(s.id)} className={`flex w-full items-center justify-between rounded-2xl p-4 text-left ${selectedStaff===s.id?'bg-[#17130f] text-white':'bg-[#f5f1ea]'}`}><div><b>{s.name}</b><div className="text-xs capitalize opacity-60">{s.role} • {outs.find(o=>o.id===s.outlet_id)?.name||'No outlet'}</div></div><span className="text-xs">{s.active?'Active':'Inactive'}</span></button>)}</div></section></div>
<section className="mt-6 rounded-3xl border border-[#e5ddd2] bg-white p-6"><div className="flex items-center gap-3"><Scissors/><div><h2 className="font-bold">Assign services to staff</h2><p className="text-xs text-[#756b62]">{selected?selected.name+' • '+(outs.find(o=>o.id===selected.outlet_id)?.name||'Outlet'):'Select a team member above'}</p></div></div>{selected&&<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visibleServices.map(s=><button key={s.id} onClick={()=>toggleAssignment(s.id)} className={`flex items-center justify-between rounded-2xl border p-4 text-left ${assigned.includes(s.id)?'border-[#17130f] bg-[#f5f1ea]':'border-[#e5ddd2]'}`}><span><b>{s.name}</b><span className="block text-xs text-[#756b62]">₹{Number(s.price).toLocaleString('en-IN')}</span></span>{assigned.includes(s.id)?<Check size={18}/>:<Plus size={18}/>}</button>)}</div>}{selected&&!visibleServices.length&&<p className="mt-6 text-sm text-[#756b62]">No services exist for this staff member's outlet yet.</p>}</section>
<section className="mt-6 rounded-3xl border border-[#e5ddd2] bg-white p-6"><h2 className="font-bold">Manage access</h2><p className="mt-2 text-sm text-[#756b62]">Deactivate a login without deleting its history.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{staff.map(s=><button key={s.id} onClick={()=>toggleUser(s)} className="flex items-center justify-between rounded-2xl border p-4 text-left"><span><b>{s.name}</b><span className="block text-xs capitalize text-[#756b62]">{s.role}</span></span><span className="text-xs">{s.active?'Deactivate':'Activate'}</span></button>)}</div></section>
</div></main>}