'use client';
import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Building2,ChevronDown,IndianRupee,LayoutDashboard,LogOut,Plus,Receipt,Settings,Users,WalletCards} from 'lucide-react';
import {supabase} from '../../lib/supabase';import {useRouter} from 'next/navigation';

type Tx={id:string;amount_paid:number;payment_mode:string;served_at:string;customers:{name:string}|null;profiles:{name:string}|null;services:{name:string}|null};
type Outlet={id:string;name:string;city:string};

export default function Dashboard(){
 const router=useRouter();const [user,setUser]=useState<any>(null);const [outlets,setOutlets]=useState<Outlet[]>([]);const [outletId,setOutletId]=useState('');const [tx,setTx]=useState<Tx[]>([]);const [loading,setLoading]=useState(true);
 async function load(id?:string){const {data:{user:u}}=await supabase.auth.getUser();if(!u){router.replace('/signin');return;}const {data:p}=await supabase.from('profiles').select('id,name,role,outlet_id').eq('id',u.id).single();if(!p||p.role==='staff'){router.replace('/staff');return;}setUser(p);const {data:o}=await supabase.from('outlets').select('id,name,city').eq('active',true).order('name');setOutlets(o||[]);const chosen=id||outletId||p.outlet_id||o?.[0]?.id;setOutletId(chosen||'');if(chosen){const {data:t}=await supabase.from('transactions').select('id,amount_paid,payment_mode,served_at,customers(name),profiles(name),services(name)').eq('outlet_id',chosen).order('served_at',{ascending:false}).limit(100);setTx((t||[]) as any);}setLoading(false);}
 useEffect(()=>{load()},[]);
 const today=useMemo(()=>{const d=new Date();return tx.filter(t=>new Date(t.served_at).toDateString()===d.toDateString())},[tx]);
 const month=useMemo(()=>{const d=new Date();return tx.filter(t=>{const x=new Date(t.served_at);return x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()})},[tx]);
 const sum=(a:Tx[])=>a.reduce((n,t)=>n+Number(t.amount_paid),0),cash=sum(today.filter(t=>t.payment_mode==='cash')),upi=sum(today.filter(t=>t.payment_mode==='upi'));
 const staff=useMemo(()=>Object.values(today.reduce((a:any,t)=>{const n=t.profiles?.name||'Unknown';a[n]??={name:n,count:0,total:0};a[n].count++;a[n].total+=Number(t.amount_paid);return a},{})).sort((a:any,b:any)=>b.total-a.total),[today]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#f5f1ea] text-sm text-[#756b62]">Loading salon workspace…</div>;
 const outlet=outlets.find(o=>o.id===outletId);
 return <div className="min-h-screen bg-[#f5f1ea] text-[#17130f]"><aside className="fixed inset-y-0 left-0 hidden w-72 bg-[#17130f] p-5 text-white lg:block"><div className="flex items-center gap-3 px-2 py-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#17130f] font-bold">HS</div><div><div className="font-bold">HAIR-SALON</div><div className="text-[9px] uppercase tracking-[.25em] text-white/40">Owner OS</div></div></div><nav className="mt-10 space-y-1">{['Overview','Transactions','Staff & Managers','Outlets','Settlements','Reports','Settings'].map((x,i)=><button key={x} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm ${i===0?'bg-white text-[#17130f] font-bold':'text-white/60'}`}>{[<LayoutDashboard/>,<Receipt/>,<Users/>,<Building2/>,<WalletCards/>,<BarChart3/>,<Settings/>][i]}{x}</button>)}</nav><button onClick={async()=>{await supabase.auth.signOut();router.replace('/signin')}} className="absolute bottom-6 left-5 flex items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/60"><LogOut size={18}/>Sign out</button></aside>
 <main className="lg:pl-72"><header className="flex justify-end border-b border-[#e5ddd2] bg-white/80 px-5 py-4 backdrop-blur"><div className="flex items-center gap-3 rounded-2xl border border-[#e5ddd2] bg-white px-4 py-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#17130f] text-xs font-bold text-white">OW</div><div><div className="text-xs font-bold">{user?.name||'Owner'}</div><div className="text-[10px] text-[#756b62]">Owner</div></div></div></header>
 <section className="mx-auto max-w-[1500px] p-5 md:p-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#b88a45]">Owner dashboard</p><h1 className="mt-2 text-4xl font-bold">Good morning, {user?.name||'Owner'}.</h1><p className="mt-2 text-sm text-[#756b62]">Live data • {outlet?.name||'All outlets'}</p></div><div className="relative"><select value={outletId} onChange={e=>{setOutletId(e.target.value);load(e.target.value)}} className="appearance-none rounded-2xl border border-[#e5ddd2] bg-white py-3 pl-4 pr-10 text-sm font-semibold">{outlets.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5" size={16}/></div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Today's sales" value={money(sum(today))} sub={today.length+' customers'} icon={<IndianRupee/>}/><Stat title="This month's sales" value={money(sum(month))} sub={month.length+' services'} icon={<BarChart3/>}/><Stat title="Today's customers" value={String(today.length)} sub="Recorded services" icon={<Users/>}/><Stat title="Cash + UPI" value={money(sum(today))} sub={money(cash)+' cash • '+money(upi)+' UPI'} icon={<WalletCards/>}/></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-3xl border border-[#e5ddd2] bg-white p-5 md:p-7"><h2 className="text-lg font-bold">Today's activity</h2><p className="mt-1 text-xs text-[#756b62]">Real transactions from Supabase</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-[#e5ddd2] text-xs text-[#756b62]"><tr>{['Customer','Staff','Service','Amount','Payment','Time'].map(h=><th key={h} className="pb-3 font-medium">{h}</th>)}</tr></thead><tbody>{today.slice(0,30).map(t=><tr key={t.id} className="border-b border-[#eee8df]"><td className="py-4 font-semibold">{t.customers?.name||'—'}</td><td className="py-4">{t.profiles?.name||'—'}</td><td className="py-4 text-[#756b62]">{t.services?.name||'—'}</td><td className="py-4 font-semibold">{money(Number(t.amount_paid))}</td><td className="py-4">{t.payment_mode.toUpperCase()}</td><td className="py-4 text-xs text-[#756b62]">{new Date(t.served_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td></tr>)}</tbody></table>{today.length===0&&<div className="py-12 text-center text-sm text-[#756b62]">No services recorded today yet.</div>}</div></div>
 <div className="space-y-6"><div className="rounded-3xl bg-[#17130f] p-6 text-white"><p className="text-xs uppercase tracking-[.2em] text-white/40">Monthly sales</p><div className="mt-3 text-4xl font-bold">{money(sum(month))}</div><div className="mt-6 text-xs text-white/50">{month.length} services recorded this month</div></div><div className="rounded-3xl border border-[#e5ddd2] bg-white p-6"><h2 className="font-bold">Staff today</h2><div className="mt-5 space-y-4">{staff.slice(0,8).map((s:any)=><div key={s.name} className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#f0e7da] text-xs font-bold">{s.name[0]}</div><div className="flex-1"><div className="flex justify-between text-sm"><span className="font-semibold">{s.name}</span><span>{money(s.total)}</span></div><div className="mt-1 text-xs text-[#756b62]">{s.count} customers served</div></div></div>)}</div>{staff.length===0&&<p className="mt-4 text-sm text-[#756b62]">No staff activity yet.</p>}</div></div></div></section></main></div>
}
function money(n:number){return '₹'+Math.round(n).toLocaleString('en-IN')}function Stat({title,value,sub,icon}:{title:string,value:string,sub:string,icon:React.ReactNode}){return <div className="rounded-3xl border border-[#e5ddd2] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-[#756b62]">{title}</span><span className="rounded-xl bg-[#f5f1ea] p-2">{icon}</span></div><div className="mt-6 text-3xl font-bold">{value}</div><div className="mt-2 text-xs text-[#8c6b43]">{sub}</div></div>}